accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('', SigUpView.as_view(), name='signup'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('accounts:login')), name='logout'),

]

djancial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('newsfeed.urls')),
    path('', include('friends.urls')),
    path('', include('todolist.urls')),
    path('home/', include('home.urls')),
    path('timeline/', include('userprofile.urls')),
    path('messages/', include('communications.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home, name="home"),
]

newsfeed/urls.py
from django.urls import path
from .views import *

app_name = "newsfeed"

urlpatterns = [
    path('post/create', PostCreateView.as_view(), name="post-create"),
    path('comment/create/<int:post_id>', create_comment, name="comment-create"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser, BaseUserManager


class CustomAccountManager(BaseUserManager):
    def create_user(self, email, password):
        user = self.model(email=email, password=password)
        user.set_password(password)
        user.is_staff = False
        user.is_superuser = False
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, username=None, gender=None):
        user = self.create_user(email=email, password=password)
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

    def get_by_natural_key(self, email):
        print(email)
        return self.get(email=email)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    GENDER_CHOICE = (
        ("Male", "Мужской"),
        ("Female", "Женский")
    )
    username = models.CharField(max_length=30, unique=True, blank=False,
                                error_messages={'unique': "Имя пользователя уже используется."})
    email = models.EmailField(unique=True, blank=False,
                              error_messages={'unique': "Пользователь с этим адресом уже зарегистрирован."})
    gender = models.CharField(max_length=7, choices=GENDER_CHOICE, blank=True)

    is_staff = models.BooleanField(default=False)

    is_superuser = models.BooleanField(default=False)

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'gender']

    def get_short_name(self):
        return self.email

    def natural_key(self):
        return self.email

    def __unicode__(self):
        return self.email

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from accounts.models import CustomUser


class SignUpForm(UserCreationForm):
    GENDER_CHOICE = (
        ("Male", "Male"),
        ("Female", "Female")
    )
    username = forms.CharField(label="Username")
    email = forms.EmailField(label="E-mail")
    gender = forms.ChoiceField(choices=GENDER_CHOICE, label="Gender")
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput())
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput())

    class Meta:
        model = CustomUser
        fields = (
            'username',
            'email',
            'gender',
            'password1',
            'password2',
        )


# class UserLoginForm(forms.Form):
#     email = forms.EmailField(label="E-mail")
#     password = forms.CharField(label="Password", strip=False, widget=forms.PasswordInput())
#
#     class Meta:
#         model = CustomUser
#         fields = (
#             'email',
#             'password',
#         )

accounts/views.py
from django.contrib import messages
from django.contrib.auth import views
from accounts.forms import *
from accounts.models import CustomUser
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic


class SigUpView(generic.CreateView):
    model = CustomUser
    form_class = SignUpForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('accounts:login')

    def get_success_url(self):
        return self.success_url

    def post(self, request, *args, **kwargs):
        if CustomUser.objects.filter(email=request.POST['email']).exists():
            messages.warning(request, 'Этот адрес уже используется.')
            return redirect('accounts:signup')

        form = SignUpForm(request.POST)
        #TODO createview tg
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get('password1')
            user.set_password(password)
            user.save()
            return redirect('accounts:login')
        else:
            print(form.errors)
            return render(request, 'accounts/signup.html', {'form': form})


class UserLoginView(views.LoginView):
    template_name = 'accounts/login.html'

home/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from friends.models import Friend
from newsfeed.models import Post


def home(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('accounts:login'))

    friends_one = Friend.objects.filter(users=request.user).filter(status='friend')
    friends_two = Friend.objects.filter(current_user=request.user).filter(status='friend')
    friends_list_one = list(friends_one.values_list('users_id', flat=True))
    friends_list_two = list(friends_two.values_list('current_user_id', flat=True))
    friends_list_id = friends_list_one + friends_list_two + [request.user.id]
    friends = friends_one.union(friends_two)
    posts = Post.objects.all()
    return render(request, 'accounts/home.html', {'posts': posts, 'friends': friends})

templates/accounts/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    {% for post in posts %}
        <p><img src="{{post.user.userprofile.profile_image.url}}" width="20" height="20">{{post.user.username}}</p>
        <div class="description">
            <p style="font-size: 25px; font-weight: bold">{{ post.body }}</p>
        </div>
        <form method="post" action="{% url 'newsfeed:comment-create' post.id%}">
            {% csrf_token %}
            <input placeholder="Post your comment" name="content">
        </form>
        <div class="coment-area">
            <ul class="we-comet">
                {% for comment in post.comments.all %}
                <li>
                    <div class="comet-avatar">
                        <img src="{% static 'images/comment.jpg' %}" alt="" style="width: 50px; height: 50px">
                    </div>
                    <div class="we-comment">
                        <div class="coment-head">
                            <h5><a href="time-line.html" title="">{{ comment.user.username }}</a></h5>
                            <span>{{ comment.created_at|timesince }} ago</span>
                        </div>
                        <p>{{ comment.content }}</p>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}

    <form method="post" action="{% url 'newsfeed:post-create' %}">
        {% csrf_token %}
        <textarea rows="2" name="body" placeholder="Write something"></textarea>
        <button type="submit">Post</button>
    </form>
{% endblock %}

templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>

    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>
<body>
<div class="theme-layout">
    <div class="container-fluid pdng0">
            <div>
                <div class="login-reg-bg">
                    <div class="log-reg-area sign">
                        <h2 class="log-title">Login</h2>

                        <form method="post" action="">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit">Login</button>
                        </form>
                    </div>
                </div>
            </div>

    </div>
</div>

<script src="js/main.min.js"></script>
<script src="js/script.js"></script>

</body>
</html>

templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>

    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>
<body>
<!--<div class="se-pre-con"></div>-->
<div class="theme-layout">
    <div class="container-fluid pdng0">
            <div>
                <div class="login-reg-bg show">
                    <div class="log-reg-area reg">

                        <form method="post" action="">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit">sign up</button>
                        </form>
                        <br/>
                        <a href="{% url 'accounts:login' %}">log in</a>
                    </div>
                </div>
            </div>
    </div>
</div>