djancial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('newsfeed.urls')),
    path('', include('friends.urls')),
    path('', include('todolist.urls')),
    path('home/', include('home.urls')),
    path('timeline/', include('userprofile.urls')),
    path('messages/', include('communications.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home, name="home"),
]

todolist/urls.py
from django.urls import path
from .views import *

app_name = "todo"

urlpatterns = [
    path('todo', todo, name="todo"),
    path('todo/create', ToDoCreateView.as_view(), name="todo-create"),
    path('todo/delete/<int:pk>', delete_todo, name="todo-delete"),
    path('todo/notifications', todo_notifications_list, name="todo_notifications"),
    path('todo/notifications/delete/<int:pk>', delete_notification, name="delete_todo_notification"),
]

notifications/models.py
from django.db import models
from accounts.models import CustomUser
from todolist.models import TodoList


class Notification(models.Model):
    todo = models.ForeignKey(TodoList, on_delete=models.CASCADE,
                             blank=True, null=True, related_name="todo_notification")
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="user_notifications")
    created_at = models.DateTimeField(auto_now_add=True)
    is_seen = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']

notifications/views.py
from django.http import JsonResponse

from friends.models import CustomNotification


def mark_like_comment_notifications_as_read(request):
    CustomNotification.objects.filter(recipient=request.user, type="comment").update(unread=False)
    return JsonResponse({
        'status': True,
        'message': "Marked all notifications as read"
    })

templates/todo/notifications.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% for notif in todo_notifications %}
<br/>
<div style="border:solid; color:grey; width:200px; margin-left:10px">
    <p style="margin-left:3px">{{notif.todo.title}}</p>
    <p style="margin-left:3px">{{notif.todo.content}}</p>
    <p style="margin-left:3px">{{notif.todo.date}}</p>
    <p><a href="{% url 'todo:delete_todo_notification' notif.pk %}">Delete</a></p>
</div>
{% endfor %}


{% endblock %}

templates/todo/todo.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<p style="margin-left:10px">Add Notes</p>
<div style="border:solid; color:grey; width:720px; margin-left:10px">
<form method="post" action="{% url 'todo:todo-create' %}" style="margin-left:5px; margin-top:2px">
    {% csrf_token %}
    <p><input type="text" name="title"></p>
    <p><input type="date" name="date"></p>
    <p><textarea rows="3" style="width:700px" name="content" placeholder="Write something"></textarea></p>
    <button type="submit">Add Note</button>
</form>
</div>

{% for todo in todos %}
<br/>
<div style="border:solid; color:grey; width:200px; margin-left:10px">
    <p style="margin-left:3px">{{todo.title}}</p>
    <p style="margin-left:3px">{{todo.content}}</p>
    <p style="margin-left:3px">{{todo.date}}</p>
    <p><a href="{% url 'todo:todo-delete' todo.pk %}">Delete</a></p>
</div>
{% endfor %}











{% endblock %}