accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('', SigUpView.as_view(), name='signup'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('accounts:login')), name='logout'),

]

djancial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('newsfeed.urls')),
    path('', include('friends.urls')),
    path('', include('todolist.urls')),
    path('home/', include('home.urls')),
    path('timeline/', include('userprofile.urls')),
    path('messages/', include('communications.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friends/urls.py
from django.urls import path
from .views import *
from search.views import search

app_name = 'friends'

urlpatterns = [
    path('find-friends', FindFriendsListView.as_view(), name="find-friends"),
    path('accept-friends', AcceptFriendsListView.as_view(), name="accept-friends"),
    path('send-request/<slug:username>', send_request, name="send-request"),
    path('accept-request/<slug:friend>', accept_request, name="accept-request"),
    path('search/', search, name='search'),

]

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home, name="home"),
]

todolist/urls.py
from django.urls import path
from .views import *

app_name = "todo"

urlpatterns = [
    path('todo', todo, name="todo"),
    path('todo/create', ToDoCreateView.as_view(), name="todo-create"),
    path('todo/delete/<int:pk>', delete_todo, name="todo-delete"),
    path('todo/notifications', todo_notifications_list, name="todo_notifications"),
    path('todo/notifications/delete/<int:pk>', delete_notification, name="delete_todo_notification"),
]

userprofile/urls.py
from django.urls import path
from userprofile.views import *

app_name = "userprofile"

urlpatterns = [
    path('edit-profile', ProfileEditView.as_view(), name="edit-profile"),
    path('profile/<slug:username>', TimeLineView.as_view(), name="user-timeline"),
]

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <title>Djancial</title>

    {% include 'includes/stylesheets.html' %}
    {% csrf_token %}

</head>
<body>
<div class="theme-layout">

    <div class="topbar stick">


        <div class="top-area">
            <ul>
                <li><a href="{% url 'home:home' %}" title="Home" data-ripple=""><i class="ti-home"></i></a></li>
                <li><a href="{% url 'communications:all-messages' %}" class="link">Messenger</a></li>
                <li><a href="{% url 'todo:todo' %}" class="link">Notes</a></li>
                <li>
                    <a href="{% url 'friends:accept-friends' %}" title="Notification" data-ripple="">
                        <i class="ti-user"></i><span id="total-friend-notifications"></span>
                    </a>

                </li>
                <li><a href="{% url 'todo:todo_notifications' %}" class="link">Notifications<sub style="color:blue;">({{notifications.count}})</sub></a></li>

            </ul>
            <div class="user-img">
                <img src="{{ request.user.userprofile.profile_image.url }}" alt="" style="height: 40px; width: 40px;">
                <span class="status f-online"></span>
                <div class="user-setting">
                    <a href="{% url 'userprofile:user-timeline' user.username %}" title=""><i class="ti-user"></i> view profile</a>
                    <a href="{% url 'userprofile:edit-profile' %}" title=""><i class="ti-pencil-alt"></i>edit profile</a>
                    <a href="{% url 'accounts:logout' %}" title=""><i class="ti-power-off"></i>log out</a>
                </div>
            </div>
        </div>
    </div>
</div>

    {% block content %}
    {% endblock %}

{% include 'includes/scripts.html' %}
{% block scripts %}{% endblock %}

</body>
</html>